import Head from 'next/head'

type HeadProps = {
  title?: string
}

export default function MyHead({ title = 'Calabouço do Android' }: HeadProps) {
  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}
